/// Flutter icons Baseline
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Baseline
///      fonts:
///       - asset: fonts/Baseline.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BaselineIcons {
  BaselineIcons._();

  static const _kFontFam = 'BaselineIcons';
  static const String? _kFontPkg = null;

  static const IconData icon_menu =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_ranking =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_court =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_home =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_tennis =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_ball =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
